"""ReportLab PDF generator for deployment orders."""

from __future__ import annotations

from datetime import date, timedelta
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


def generate_deployment_order_pdf(
    narrative: dict,
    district_code: str,
    deployment_id: str,
) -> bytes:
    """
    Generate a PDF deployment order using ReportLab.

    Args:
        narrative: Gemini-generated order narrative dict
        district_code: District code (e.g. NDB01)
        deployment_id: UUID of the deployment

    Returns bytes of the generated PDF.
    """
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=2.5 * cm,
        rightMargin=2.5 * cm,
        topMargin=2.5 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "EduTitle",
        parent=styles["Heading1"],
        fontSize=14,
        spaceAfter=6,
        alignment=1,  # center
        textColor=colors.HexColor("#1e3a5f"),
    )
    body_style = ParagraphStyle(
        "EduBody",
        parent=styles["Normal"],
        fontSize=10,
        leading=14,
        spaceAfter=8,
    )
    sub_style = ParagraphStyle(
        "EduSub",
        parent=styles["Normal"],
        fontSize=9,
        textColor=colors.grey,
        alignment=1,
    )

    story = []

    # Header
    story.append(Paragraph("Maharashtra Shasan", title_style))
    story.append(Paragraph("School Education & Sports Department", sub_style))
    story.append(Paragraph(f"District: Nandurbar ({district_code})", sub_style))
    story.append(Spacer(1, 0.3 * cm))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#1e3a5f")))
    story.append(Spacer(1, 0.3 * cm))

    order_num = narrative.get("order_number", f"NDB/DEO/{date.today().year}/{deployment_id[:8].upper()}")
    effective = narrative.get("effective_date", (date.today() + timedelta(days=14)).isoformat())

    story.append(Paragraph(f"TEACHER DEPLOYMENT ORDER", title_style))
    story.append(Paragraph(f"Order No: {order_num}", body_style))
    story.append(Paragraph(f"Date: {date.today().strftime('%d %B %Y')}", body_style))
    story.append(Paragraph(f"Effective Date: {effective}", body_style))
    story.append(Spacer(1, 0.4 * cm))

    # Narrative
    narrative_text = narrative.get("narrative", "Deployment order generated by EduAllocPro AI system.")
    story.append(Paragraph(narrative_text, body_style))
    story.append(Spacer(1, 0.4 * cm))

    # Marathi narrative
    marathi_text = narrative.get("marathi_narrative", "")
    if marathi_text:
        story.append(HRFlowable(width="100%", thickness=1, color=colors.lightgrey))
        story.append(Spacer(1, 0.2 * cm))
        marathi_style = ParagraphStyle(
            "MarathiBody", parent=body_style, fontName="Helvetica", fontSize=9
        )
        story.append(Paragraph(marathi_text, marathi_style))
        story.append(Spacer(1, 0.4 * cm))

    # Signature block
    story.append(Spacer(1, 1 * cm))
    story.append(HRFlowable(width="40%", thickness=1, color=colors.black))
    story.append(Paragraph(narrative.get("signed_by", "District Education Officer, Nandurbar"), body_style))
    story.append(Paragraph(f"Powered by EduAllocPro · Deployment ID: {deployment_id[:8]}", sub_style))

    doc.build(story)
    return buf.getvalue()
